build: integrate whiskers
PanAeon/drracket-catppuccin pull request #4
Opened 2024-04-02 19:36 UTC by nullishamy

2024-10-28 00:34 UTC, sgoudham commented
Hey :wave: @PanAeon,

Are you happy for this PR to be merged? Whiskers is being rolled out across the organisation to make it easier to update themes when/if the hex codes of the theme need changing or updating.

I see that this port is uploaded to the [drracket package registry](https://pkgs.racket-lang.org/package/drracket-catppuccin). Since this port has been merged, we usually take ownership of plugins from an organisational level to avoid relying on a single maintainer to make updates. Do you know if you would be able to transfer the package to a shared Catppuccin account?

2024-10-28 08:40 UTC, PanAeon commented
Hi, yeah, I'm totally fine. I can just delete my package after you upload it to the package registry.

2024-10-29 11:15 UTC, sgoudham commented on info.rkt
> +  (define mocha-crust)    #(17 17 27)
Looks like these need to end in 2 `))` instead of just 1 `)`

2024-10-29 11:15 UTC, sgoudham requested changes
Template needs edited as per my comment above.

2024-11-11 08:29 UTC, sgoudham approved these changes

2024-11-11 08:30 UTC, merged

2024-11-11 12:43 UTC, sgoudham commented
Hi again @PanAeon,

I've renamed the package as part of this PR to be `catppuccin-theme` and uploaded it to the package registry.

I'd appreciate if you could confirm that you can install the new package locally and then afterwards remove the `drracket-catppuccin` package. 

Thanks for your work again on this repository!

2024-11-21 13:22 UTC, PanAeon commented
hey @sgoudham 
I have deleted my package from the registry.
Everything works except the repo name `drracket` clashes with `drracket`. I've created and issue for this. I'm not an expert on racket so can't help with details.